name: stock_path_tracker
channels:
- anaconda
- conda-forge
dependencies:
- python=3.8.0
- pandas==0.25.3
- numpy==1.18.5
- matplotlib==3.2.2
- jupyter==1.0.0
- jupyterlab==2.1.5
- jupyterlab_code_formatter==1.3.4
- nodejs==10.13.0
- tqdm==4.47.0
- pip==20.1.1
- pip:
        - dolphindb==0.1.15.20

